#!/usr/bin/env python3
"""Generate the expanded factual_recall.json with 1000 questions (250 per category)."""

import json
from pathlib import Path

# ---------------------------------------------------------------------------
# Category: EASY  (common knowledge — model should NOT need search)
# ---------------------------------------------------------------------------
EASY = [
    # --- World capitals ---
    ("What is the capital of France?", "Paris"),
    ("What is the capital of Japan?", "Tokyo"),
    ("What is the capital of Australia?", "Canberra"),
    ("What is the capital of Brazil?", "Brasilia"),
    ("What is the capital of Canada?", "Ottawa"),
    ("What is the capital of Egypt?", "Cairo"),
    ("What is the capital of Germany?", "Berlin"),
    ("What is the capital of India?", "New Delhi"),
    ("What is the capital of Italy?", "Rome"),
    ("What is the capital of Mexico?", "Mexico City"),
    ("What is the capital of Russia?", "Moscow"),
    ("What is the capital of South Korea?", "Seoul"),
    ("What is the capital of Spain?", "Madrid"),
    ("What is the capital of Turkey?", "Ankara"),
    ("What is the capital of Argentina?", "Buenos Aires"),
    ("What is the capital of Thailand?", "Bangkok"),
    ("What is the capital of Kenya?", "Nairobi"),
    ("What is the capital of Sweden?", "Stockholm"),
    ("What is the capital of Peru?", "Lima"),
    ("What is the capital of Poland?", "Warsaw"),
    ("What is the capital of South Africa?", "Pretoria (executive capital)"),
    ("What is the capital of Greece?", "Athens"),
    ("What is the capital of Portugal?", "Lisbon"),
    ("What is the capital of Norway?", "Oslo"),
    ("What is the capital of Ireland?", "Dublin"),
    ("What is the capital of Colombia?", "Bogota"),
    ("What is the capital of Chile?", "Santiago"),
    ("What is the capital of Vietnam?", "Hanoi"),
    ("What is the capital of the Philippines?", "Manila"),
    ("What is the capital of Finland?", "Helsinki"),

    # --- Famous people / history ---
    ("Who wrote the play Romeo and Juliet?", "William Shakespeare"),
    ("Who painted the Mona Lisa?", "Leonardo da Vinci"),
    ("Who was the first person to walk on the Moon?", "Neil Armstrong"),
    ("Who developed the theory of general relativity?", "Albert Einstein"),
    ("Who is known as the father of computer science?", "Alan Turing"),
    ("Who wrote 'A Brief History of Time'?", "Stephen Hawking"),
    ("Who discovered penicillin?", "Alexander Fleming"),
    ("Who wrote 'The Origin of Species'?", "Charles Darwin"),
    ("Who composed the Four Seasons?", "Antonio Vivaldi"),
    ("Who was the first President of the United States?", "George Washington"),
    ("Who invented the telephone?", "Alexander Graham Bell"),
    ("Who wrote 'Pride and Prejudice'?", "Jane Austen"),
    ("Who painted 'Starry Night'?", "Vincent van Gogh"),
    ("Who discovered gravity?", "Isaac Newton"),
    ("Who wrote 'The Communist Manifesto'?", "Karl Marx and Friedrich Engels"),
    ("Who was the first woman to win a Nobel Prize?", "Marie Curie"),
    ("Who composed the Ninth Symphony?", "Ludwig van Beethoven"),
    ("Who wrote '1984'?", "George Orwell"),
    ("Who founded Microsoft?", "Bill Gates and Paul Allen"),
    ("Who was the 16th President of the United States?", "Abraham Lincoln"),
    ("Who sculpted David?", "Michelangelo"),
    ("Who wrote 'Don Quixote'?", "Miguel de Cervantes"),
    ("Who invented the light bulb?", "Thomas Edison"),
    ("Who founded Apple Inc.?", "Steve Jobs, Steve Wozniak, and Ronald Wayne"),
    ("Who wrote 'To Kill a Mockingbird'?", "Harper Lee"),

    # --- Basic science ---
    ("What is the chemical symbol for gold?", "Au"),
    ("What is the boiling point of water in Celsius?", "100 degrees Celsius"),
    ("What is the speed of light in a vacuum?", "approximately 299,792 kilometers per second"),
    ("What element does 'O' represent on the periodic table?", "Oxygen"),
    ("What is the atomic number of carbon?", "6"),
    ("What does DNA stand for?", "Deoxyribonucleic acid"),
    ("What is the formula for water?", "H2O"),
    ("What is the chemical symbol for iron?", "Fe"),
    ("What is the chemical symbol for sodium?", "Na"),
    ("What is the atomic number of hydrogen?", "1"),
    ("What planet is closest to the Sun?", "Mercury"),
    ("What gas do plants absorb from the atmosphere?", "Carbon dioxide (CO2)"),
    ("What is the chemical formula for table salt?", "NaCl"),
    ("What is the hardest natural substance on Earth?", "Diamond"),
    ("What is the chemical symbol for silver?", "Ag"),
    ("How many chromosomes do humans have?", "46 (23 pairs)"),
    ("What is the pH of pure water?", "7"),
    ("What is the most abundant gas in Earth's atmosphere?", "Nitrogen (approximately 78%)"),
    ("What type of bond holds water molecules together?", "Covalent bonds (within the molecule) and hydrogen bonds (between molecules)"),
    ("What organelle is known as the powerhouse of the cell?", "Mitochondria"),

    # --- Geography basics ---
    ("What is the largest planet in our solar system?", "Jupiter"),
    ("What is the longest river in the world?", "The Nile (approximately 6,650 km)"),
    ("What is the tallest mountain in the world?", "Mount Everest (8,849 meters)"),
    ("How many continents are there on Earth?", "7"),
    ("What is the largest ocean on Earth?", "Pacific Ocean"),
    ("What is the smallest country in the world by area?", "Vatican City"),
    ("What is the largest desert in the world?", "Sahara Desert (largest hot desert) or Antarctic Desert (largest overall)"),
    ("What is the largest country in the world by area?", "Russia"),
    ("What is the deepest ocean in the world?", "Pacific Ocean"),
    ("Which continent is the driest?", "Antarctica"),
    ("What is the largest freshwater lake by surface area?", "Lake Superior"),
    ("On which continent is the Amazon Rainforest located?", "South America"),
    ("What is the largest island in the world?", "Greenland"),
    ("Which ocean lies between Africa and Australia?", "Indian Ocean"),
    ("What is the highest waterfall in the world?", "Angel Falls in Venezuela (979 meters)"),

    # --- Math / numbers ---
    ("What is the square root of 144?", "12"),
    ("What is the value of pi to two decimal places?", "3.14"),
    ("How many sides does a hexagon have?", "6"),
    ("What is 7 squared?", "49"),
    ("What is a prime number?", "A number greater than 1 that has no positive divisors other than 1 and itself"),
    ("How many degrees are in a circle?", "360"),
    ("What is the Fibonacci sequence?", "A sequence where each number is the sum of the two preceding ones: 0, 1, 1, 2, 3, 5, 8, 13, ..."),
    ("How many sides does a pentagon have?", "5"),
    ("What is the Roman numeral for 50?", "L"),
    ("What is the Roman numeral for 1000?", "M"),

    # --- General knowledge ---
    ("What year did World War II end?", "1945"),
    ("In what year did the Titanic sink?", "1912"),
    ("What year was the Declaration of Independence signed?", "1776"),
    ("What language is primarily spoken in Brazil?", "Portuguese"),
    ("What is the currency of the United Kingdom?", "Pound sterling (GBP)"),
    ("What currency is used in Japan?", "Japanese yen (JPY)"),
    ("How many days are in a leap year?", "366"),
    ("How many minutes are in an hour?", "60"),
    ("How many bones are in the adult human body?", "206"),
    ("What blood type is known as the universal donor?", "O negative"),
    ("What is the largest organ of the human body?", "Skin"),
    ("How many teeth does an adult human typically have?", "32"),
    ("What are the three primary colors of light?", "Red, green, and blue"),
    ("What is the freezing point of water in Fahrenheit?", "32 degrees Fahrenheit"),
    ("What does HTTP stand for?", "HyperText Transfer Protocol"),
    ("What does CPU stand for?", "Central Processing Unit"),
    ("What programming language was created by Guido van Rossum?", "Python"),
    ("What does HTML stand for?", "HyperText Markup Language"),
    ("In which sport is a shuttlecock used?", "Badminton"),
    ("How many players are on a standard soccer team on the field?", "11"),
    ("What is the national sport of Japan?", "Sumo wrestling"),
    ("In tennis, what is a score of zero called?", "Love"),
    ("How many strings does a standard guitar have?", "6"),
    ("What is the largest bird in the world?", "Ostrich"),
    ("What is the fastest land animal?", "Cheetah"),
    ("What is the largest mammal in the world?", "Blue whale"),
    ("What is the smallest bone in the human body?", "Stapes (in the ear)"),
    ("What vitamin does the body produce when exposed to sunlight?", "Vitamin D"),
    ("Which planet is known as the Red Planet?", "Mars"),
    ("What is the nearest star to Earth?", "The Sun"),
    ("How many planets are in our solar system?", "8"),
    ("What is the brightest planet visible from Earth?", "Venus"),
    ("Which planet has the most moons?", "Saturn"),
    ("What galaxy do we live in?", "The Milky Way"),
    ("What is the name of Earth's natural satellite?", "The Moon"),
    ("What are the four states of matter?", "Solid, liquid, gas, and plasma"),
    ("What does UNESCO stand for?", "United Nations Educational, Scientific and Cultural Organization"),
    ("What does NASA stand for?", "National Aeronautics and Space Administration"),
    ("What is the most widely spoken language in the world by total speakers?", "English (by total speakers including non-native)"),
    ("Who wrote 'The Great Gatsby'?", "F. Scott Fitzgerald"),
    ("Who wrote 'War and Peace'?", "Leo Tolstoy"),
    ("Who wrote 'Hamlet'?", "William Shakespeare"),
    ("What country gifted the Statue of Liberty to the United States?", "France"),
    ("What year did the Berlin Wall fall?", "1989"),
    ("In what year did World War I begin?", "1914"),
    ("What is the most commonly spoken first language in the world?", "Mandarin Chinese"),
    ("How many keys are on a standard piano?", "88"),
    ("What is the longest bone in the human body?", "Femur"),
    ("What continent is Egypt in?", "Africa"),
    ("What is the currency of the European Union?", "Euro (EUR)"),
    ("What is the chemical formula for carbon dioxide?", "CO2"),
    ("What is the symbol for potassium on the periodic table?", "K"),
    ("What is the most abundant element in the universe?", "Hydrogen"),
    ("In what year did humans first land on the Moon?", "1969"),
    ("Who painted the ceiling of the Sistine Chapel?", "Michelangelo"),
    ("What is the official language of Brazil?", "Portuguese"),
    ("How many stripes are on the American flag?", "13"),
    ("What is the national animal of Australia?", "Kangaroo (one of two, along with the emu)"),
    ("What is the tallest animal in the world?", "Giraffe"),
    ("How many colors are in a rainbow?", "7"),
    ("What is the currency of India?", "Indian rupee (INR)"),
    ("What is the world's most widely practiced religion by number of followers?", "Christianity"),
    ("What year did the French Revolution begin?", "1789"),
    ("Who wrote 'Crime and Punishment'?", "Fyodor Dostoevsky"),
    ("What is the capital of the United States?", "Washington, D.C."),
    ("What is the capital of China?", "Beijing"),
    ("What is the capital of the United Kingdom?", "London"),
    ("What is the largest continent by area?", "Asia"),
    ("What is the smallest continent by area?", "Australia (or Oceania depending on definition)"),
    ("Who composed 'The Magic Flute'?", "Wolfgang Amadeus Mozart"),
    ("What is the speed of sound in air at sea level?", "approximately 343 meters per second"),
    ("What is the currency of China?", "Renminbi (yuan, CNY)"),
    ("What is the main ingredient in traditional Japanese miso soup?", "Fermented soybean paste (miso)"),
    ("In which country is the Great Barrier Reef located?", "Australia"),
    ("What is the largest organ inside the human body?", "Liver"),
    # --- More easy (75 more) ---
    ("What is the capital of Denmark?", "Copenhagen"),
    ("What is the capital of Austria?", "Vienna"),
    ("What is the capital of Hungary?", "Budapest"),
    ("What is the capital of Czech Republic?", "Prague"),
    ("What is the capital of Romania?", "Bucharest"),
    ("What is the capital of Morocco?", "Rabat"),
    ("What is the capital of New Zealand?", "Wellington"),
    ("What is the capital of Cuba?", "Havana"),
    ("What is the capital of Malaysia?", "Kuala Lumpur"),
    ("What is the capital of Nigeria?", "Abuja"),
    ("What is the capital of Pakistan?", "Islamabad"),
    ("What is the capital of Indonesia?", "Jakarta (moving to Nusantara)"),
    ("What is the capital of Iraq?", "Baghdad"),
    ("What is the capital of Ukraine?", "Kyiv"),
    ("What is the capital of Bangladesh?", "Dhaka"),
    ("Who wrote 'The Odyssey'?", "Homer"),
    ("Who wrote 'Les Misérables'?", "Victor Hugo"),
    ("Who wrote 'The Divine Comedy'?", "Dante Alighieri"),
    ("Who composed 'The Nutcracker'?", "Pyotr Ilyich Tchaikovsky"),
    ("Who painted 'The Persistence of Memory'?", "Salvador Dalí"),
    ("Who painted 'The Scream'?", "Edvard Munch"),
    ("Who painted 'Girl with a Pearl Earring'?", "Johannes Vermeer"),
    ("Who wrote 'One Hundred Years of Solitude'?", "Gabriel García Márquez"),
    ("Who wrote 'The Catcher in the Rye'?", "J.D. Salinger"),
    ("Who invented the World Wide Web?", "Tim Berners-Lee"),
    ("What is the chemical symbol for lead?", "Pb"),
    ("What is the chemical symbol for mercury?", "Hg"),
    ("What is the chemical symbol for tin?", "Sn"),
    ("What is the chemical symbol for copper?", "Cu"),
    ("What is the chemical symbol for tungsten?", "W"),
    ("What is the second most abundant element in Earth's crust?", "Silicon"),
    ("What type of rock is marble?", "Metamorphic rock"),
    ("What is the process by which plants make food using sunlight?", "Photosynthesis"),
    ("What is the largest species of shark?", "Whale shark"),
    ("What is the smallest planet in our solar system?", "Mercury"),
    ("Which planet has the Great Red Spot?", "Jupiter"),
    ("What is the name of the galaxy nearest to the Milky Way?", "Andromeda Galaxy"),
    ("What does RAM stand for in computing?", "Random Access Memory"),
    ("What does GPS stand for?", "Global Positioning System"),
    ("What does JPEG stand for?", "Joint Photographic Experts Group"),
    ("Who was the ancient Greek god of the sea?", "Poseidon"),
    ("What is the largest species of penguin?", "Emperor penguin"),
    ("What is the largest species of bear?", "Polar bear (or Kodiak bear by some measures)"),
    ("In which country did the Renaissance begin?", "Italy"),
    ("What is the hardest mineral on the Mohs scale?", "Diamond (10)"),
    ("How many chambers does the human heart have?", "4 chambers"),
    ("What is the main language spoken in Iran?", "Persian (Farsi)"),
    ("What is the main language spoken in Ethiopia?", "Amharic (official)"),
    ("What is sushi traditionally wrapped in?", "Nori (seaweed)"),
    ("What instrument has 88 keys?", "Piano"),
    ("What year did the Cold War end?", "1991 (dissolution of the Soviet Union)"),
    ("What year did the Korean War begin?", "1950"),
    ("What year was the United Nations founded?", "1945"),
    ("What year did India gain independence from Britain?", "1947"),
    ("What is the largest species of cat?", "Tiger"),
    ("What is the only mammal capable of true flight?", "Bat"),
    ("What gas makes up about 21% of Earth's atmosphere?", "Oxygen"),
    ("What is the most common blood type?", "O positive"),
    ("Who invented the printing press in Europe?", "Johannes Gutenberg"),
    ("What country has the most time zones?", "France (12 time zones including overseas territories)"),
    ("What is the southernmost continent?", "Antarctica"),
    ("Which country is known as the Land of the Rising Sun?", "Japan"),
    ("What is the national flower of Japan?", "Cherry blossom (sakura)"),
    ("How many players are on a basketball team on the court?", "5"),
    ("What sport is played at Wimbledon?", "Tennis"),
    ("What is the largest bone in the human body?", "Femur (thigh bone)"),
    ("What vitamin is found in citrus fruits?", "Vitamin C"),
    ("What is the currency of Switzerland?", "Swiss franc (CHF)"),
    ("Who wrote 'The Art of War'?", "Sun Tzu"),
    ("What planet is known for its rings?", "Saturn"),
    ("What is the most widely used programming language in web development?", "JavaScript"),
    ("What is the name of the longest-running animated TV show in the US?", "The Simpsons"),
    ("What is the capital of Slovakia?", "Bratislava"),
    ("What is the capital of Serbia?", "Belgrade"),
    ("What is the capital of Bulgaria?", "Sofia"),
]

# ---------------------------------------------------------------------------
# Category: HARD  (obscure specifics — model SHOULD need search)
# ---------------------------------------------------------------------------
HARD = [
    # --- Precise measurements / dimensions ---
    ("What is the exact elevation in meters of the highest point in Luxembourg?", "Kneiff at 560 meters"),
    ("What is the wingspan in meters of a Boeing 747-8?", "68.4 meters"),
    ("What is the deepest point of the Mariana Trench in meters?", "approximately 10,935 meters (Challenger Deep)"),
    ("What is the exact melting point of titanium in degrees Celsius?", "1,668 degrees Celsius"),
    ("What is the total area of Lake Baikal in square kilometers?", "approximately 31,722 square kilometers"),
    ("What is the average depth of the Mediterranean Sea in meters?", "approximately 1,500 meters"),
    ("What is the total length of the Great Wall of China in kilometers according to the most recent survey?", "approximately 21,196 kilometers (including all branches and sections)"),
    ("What is the total length of the Trans-Siberian Railway in kilometers?", "approximately 9,289 kilometers"),
    ("What is the exact height of the Burj Khalifa in meters?", "828 meters"),
    ("What is the exact length of the Suez Canal in kilometers?", "approximately 193.3 kilometers"),
    ("What is the exact diameter of the Moon in kilometers?", "approximately 3,474 kilometers"),
    ("What is the total length of the Danube River in kilometers?", "approximately 2,850 kilometers"),
    ("What is the exact height of the CN Tower in Toronto in meters?", "553 meters"),
    ("What is the surface area of Mars in square kilometers?", "approximately 144.8 million square kilometers"),
    ("What is the exact height of the Statue of Liberty from base to torch?", "approximately 93 meters (305 feet) including pedestal"),
    ("What is the total area of the Caspian Sea in square kilometers?", "approximately 371,000 square kilometers"),
    ("What is the exact length of the Channel Tunnel in kilometers?", "approximately 50.45 kilometers"),
    ("What is the exact elevation of Mount Kilimanjaro's highest peak in meters?", "5,895 meters (Uhuru Peak)"),
    ("What is the total length of the Yangtze River in kilometers?", "approximately 6,300 kilometers"),
    ("What is the exact depth of Lake Baikal in meters?", "approximately 1,642 meters"),
    ("What is the total area of the Gobi Desert in square kilometers?", "approximately 1,295,000 square kilometers"),
    ("What is the exact height of the Gateway Arch in St. Louis in meters?", "approximately 192 meters (630 feet)"),
    ("What is the exact diameter of Earth at the equator in kilometers?", "approximately 12,756 kilometers"),
    ("What is the total length of the Mississippi River in kilometers?", "approximately 3,766 kilometers"),
    ("What is the exact height of the Petronas Twin Towers in meters?", "451.9 meters"),
    ("What is the exact wingspan of an Airbus A380 in meters?", "79.75 meters"),
    ("What is the total area of the Black Sea in square kilometers?", "approximately 436,400 square kilometers"),
    ("What is the exact length of the Golden Gate Bridge's main span in meters?", "approximately 1,280 meters"),
    ("What is the total length of the Rhine River in kilometers?", "approximately 1,230 kilometers"),
    ("What is the exact height of One World Trade Center in meters?", "541 meters"),

    # --- Specific counts / quantities ---
    ("How many islands make up the Maldives?", "approximately 1,192 coral islands"),
    ("How many known species of ants exist worldwide?", "over 22,000 described species"),
    ("How many volumes are in the Library of Congress as of 2024?", "approximately 17 million volumes"),
    ("How many UNESCO World Heritage Sites does Italy have?", "59 as of 2024"),
    ("How many paintings did Johannes Vermeer produce in his lifetime?", "approximately 34-36 attributed works"),
    ("How many steps are there in the Eiffel Tower from ground to top?", "1,665 steps to the top"),
    ("What is the total number of subway stations in the Tokyo Metro system?", "180 stations (Tokyo Metro only, not including Toei)"),
    ("How many bones does a domestic cat have?", "approximately 230 bones"),
    ("What is the total number of municipalities in Switzerland?", "approximately 2,136 as of 2024"),
    ("How many verses are in the Quran?", "6,236 verses (ayahs)"),
    ("How many locks are in the Panama Canal?", "12 locks (in 3 sets of 2 lanes each, with the newer Neopanamax locks)"),
    ("What is the total number of kanji characters in the Joyo Kanji list in Japan?", "2,136 characters"),
    ("How many official languages does South Africa have?", "11 official languages"),
    ("How many symphonies did Gustav Mahler compose?", "9 completed symphonies (10th left unfinished)"),
    ("How many registered voters were there in Bhutan's 2023 National Assembly election?", "approximately 484,000 registered voters"),
    ("How many sonnets did Shakespeare write?", "154 sonnets"),
    ("How many rooms are in the Palace of Versailles?", "approximately 2,300 rooms"),
    ("How many islands make up the Philippines?", "approximately 7,641 islands"),
    ("How many metro stations are in the Paris Metro system?", "308 stations"),
    ("How many chapters are in the Bhagavad Gita?", "18 chapters"),
    ("How many books are in the Hebrew Bible (Tanakh)?", "24 books"),
    ("How many movements are in Beethoven's Ninth Symphony?", "4 movements"),
    ("How many stone heads (moai) are on Easter Island?", "approximately 887 moai"),
    ("How many plays did Sophocles write?", "approximately 123, of which 7 survive complete"),
    ("How many bridges span the Seine in Paris?", "37 bridges"),
    ("How many operas did Giuseppe Verdi compose?", "28 operas"),
    ("How many federally recognized Native American tribes are there in the United States?", "574 as of 2024"),
    ("How many arches are in the Roman Colosseum's exterior?", "240 arches across 3 stories"),
    ("How many moons does Uranus have?", "27 known moons"),
    ("How many works did Johann Sebastian Bach compose in total?", "over 1,100 known compositions"),

    # --- Historical dates / obscure history ---
    ("What is the exact year the University of Bologna was founded?", "1088"),
    ("In what year was the Gutenberg printing press invented?", "approximately 1440"),
    ("What year was the Rosetta Stone discovered?", "1799"),
    ("In what year was the Hagia Sophia originally completed as a cathedral?", "537 AD"),
    ("What year was the first transatlantic telegraph cable successfully laid?", "1858"),
    ("In what year was Machu Picchu built?", "approximately 1450 AD"),
    ("What year did the Byzantine Empire fall?", "1453"),
    ("In what year was the first modern Olympic Games held?", "1896 in Athens"),
    ("What year was the Magna Carta signed?", "1215"),
    ("In what year was the Suez Canal opened?", "1869"),
    ("What year was the Panama Canal completed?", "1914"),
    ("In what year was the Great Fire of London?", "1666"),
    ("What year was the Treaty of Westphalia signed?", "1648"),
    ("In what year did the Chernobyl disaster occur?", "1986"),
    ("What year was the first successful human heart transplant performed?", "1967"),
    ("In what year was the first photograph ever taken?", "1826 or 1827 by Joseph Nicéphore Niépce"),
    ("What year was the first email sent?", "1971 by Ray Tomlinson"),
    ("In what year was the Eiffel Tower completed?", "1889"),
    ("What year was the first public radio broadcast made?", "1920"),
    ("In what year was the Dead Sea Scrolls discovered?", "1947"),

    # --- Technical specifications ---
    ("What is the exact orbital period of Saturn around the Sun in Earth years?", "approximately 29.46 Earth years"),
    ("What is the orbital period of Halley's Comet in years?", "approximately 75-79 years"),
    ("What is the escape velocity from Earth's surface in km/s?", "approximately 11.2 km/s"),
    ("What is the boiling point of mercury in degrees Celsius?", "approximately 356.7 degrees Celsius"),
    ("What is the density of lead in grams per cubic centimeter?", "approximately 11.34 g/cm³"),
    ("What is the half-life of carbon-14 in years?", "approximately 5,730 years"),
    ("What is the melting point of tungsten in degrees Celsius?", "approximately 3,422 degrees Celsius"),
    ("What is the speed of sound in water in meters per second?", "approximately 1,480 meters per second"),
    ("What is the boiling point of nitrogen in degrees Celsius?", "approximately -195.8 degrees Celsius"),
    ("What is the wavelength of visible red light in nanometers?", "approximately 620-750 nanometers"),
    ("What is the gravitational acceleration on the Moon's surface?", "approximately 1.62 m/s²"),
    ("What is the melting point of gold in degrees Celsius?", "approximately 1,064 degrees Celsius"),
    ("What is the freezing point of ethanol in degrees Celsius?", "approximately -114 degrees Celsius"),
    ("What is the thermal conductivity of copper in W/(m·K)?", "approximately 401 W/(m·K)"),
    ("What is the specific heat capacity of water in J/(g·°C)?", "approximately 4.186 J/(g·°C)"),

    # --- Obscure geography / culture ---
    ("What is the name of the smallest country in Africa by area?", "Seychelles"),
    ("What is the longest fjord in Norway?", "Sognefjorden at approximately 204 kilometers"),
    ("What is the deepest cave in the world?", "Veryovkina Cave in Georgia at approximately 2,212 meters"),
    ("What is the highest capital city in the world by elevation?", "La Paz, Bolivia at approximately 3,640 meters (seat of government); Sucre is the constitutional capital"),
    ("What is the driest inhabited place on Earth?", "Arica, Chile (or Atacama Desert region)"),
    ("What is the largest landlocked country in the world?", "Kazakhstan"),
    ("What is the shortest river in the world?", "Roe River in Montana at approximately 61 meters (disputed; also D River in Oregon)"),
    ("What is the name of the world's oldest known living tree species?", "Bristlecone pine (Pinus longaeva)"),
    ("What is the saltiest body of water on Earth?", "Don Juan Pond in Antarctica"),
    ("What is the world's largest monolithic rock?", "Mount Augustus in Western Australia"),
    ("What is the northernmost capital city in the world?", "Reykjavik, Iceland"),
    ("What is the most remote inhabited island in the world?", "Tristan da Cunha"),
    ("What is the wettest place on Earth by average annual rainfall?", "Mawsynram, India (approximately 11,871 mm per year)"),
    ("What is the largest volcanic lake in the world?", "Lake Toba in Sumatra, Indonesia"),
    ("What is the longest cave system in the world?", "Mammoth Cave in Kentucky at over 680 kilometers mapped"),

    # --- Institutional / cultural specifics ---
    ("How many member states does the United Nations have?", "193 member states"),
    ("How many times zones does Russia span?", "11 time zones"),
    ("How many prefectures does Japan have?", "47 prefectures"),
    ("How many states and territories does Australia have?", "6 states and 2 mainland territories"),
    ("How many cantons does Switzerland have?", "26 cantons"),
    ("How many provinces does China have?", "23 provinces (PRC claims), 5 autonomous regions, 4 municipalities, 2 SARs"),
    ("How many emirates make up the United Arab Emirates?", "7 emirates"),
    ("How many states does Brazil have?", "26 states plus 1 federal district"),
    ("How many departments does France have?", "101 departments (96 in metropolitan France, 5 overseas)"),
    ("How many provinces does Canada have?", "10 provinces and 3 territories"),

    # --- More obscure facts ---
    ("What is the tallest tree species in the world?", "Coast redwood (Sequoia sempervirens); tallest known individual is Hyperion at about 116 meters"),
    ("What is the oldest university in the world still in operation?", "University of Bologna, founded in 1088"),
    ("What is the largest diamond ever found?", "Cullinan Diamond at 3,106 carats (uncut)"),
    ("What was the deadliest earthquake in recorded history?", "1556 Shaanxi earthquake in China, estimated 830,000 deaths"),
    ("What is the longest-running Broadway show of all time?", "The Phantom of the Opera (1988-2023, over 13,900 performances)"),
    ("What is the largest known prime number as of 2024?", "2^136,279,841 − 1 (a Mersenne prime with over 41 million digits)"),
    ("How many bones does a newborn baby have?", "approximately 270-300 bones"),
    ("What is the deepest point in the Atlantic Ocean?", "Puerto Rico Trench at approximately 8,376 meters"),
    ("What is the tallest waterfall in Africa?", "Tugela Falls in South Africa at approximately 948 meters"),
    ("What is the largest stadium in the world by capacity?", "Narendra Modi Stadium (Motera) in Ahmedabad, India at approximately 132,000"),
    ("What is the total length of the Tokyo subway system in kilometers?", "approximately 304 kilometers (Tokyo Metro and Toei combined)"),
    ("What is the oldest known city in the world still continuously inhabited?", "Damascus, Syria (approximately 10,000-12,000 years old)"),
    ("How many works are in the Louvre Museum's collection?", "approximately 380,000 objects, of which 35,000 are on display"),
    ("What was the first country to grant women the right to vote?", "New Zealand in 1893"),
    ("How many languages does the European Union have as official languages?", "24 official languages"),
    ("What is the tallest building in Africa?", "Iconic Tower in Egypt's New Administrative Capital at approximately 385 meters"),
    ("How many national parks does the United States have?", "63 national parks"),
    ("What is the coldest temperature ever recorded on Earth?", "approximately -89.2°C at Vostok Station, Antarctica in 1983"),
    ("What is the hottest temperature ever recorded on Earth?", "approximately 56.7°C (134°F) in Death Valley, California in 1913"),
    ("What is the most spoken constructed language in the world?", "Esperanto"),
    ("How many symphonies did Joseph Haydn compose?", "106 symphonies"),
    ("What is the smallest mammal in the world by weight?", "Etruscan shrew (approximately 1.8 grams)"),
    ("How many words are in the complete works of Shakespeare?", "approximately 884,000 words"),
    ("What is the longest word in the English language found in major dictionaries?", "Pneumonoultramicroscopicsilicovolcanoconiosis (45 letters)"),
    ("How many elements are in the periodic table as of 2024?", "118 confirmed elements"),
    ("What is the deepest lake in Africa?", "Lake Tanganyika at approximately 1,470 meters"),
    ("How many time zones does the United States have (including territories)?", "9 time zones (including territories)"),
    ("What is the oldest national park in the world?", "Yellowstone National Park, established 1872"),
    ("How many symphonies did Mozart compose?", "41 numbered symphonies"),
    ("What is the total number of UNESCO World Heritage Sites worldwide as of 2024?", "approximately 1,199 sites"),
    # --- More hard (100 more) ---
    ("What is the exact height of the Tokyo Skytree in meters?", "634 meters"),
    ("What is the total length of the Nile River in kilometers?", "approximately 6,650 kilometers"),
    ("What is the exact area of Vatican City in square kilometers?", "approximately 0.44 square kilometers"),
    ("What is the length of the Hoover Dam in meters?", "approximately 379 meters (1,244 feet) along the crest"),
    ("What is the exact distance from Earth to the Moon in kilometers?", "approximately 384,400 kilometers (average)"),
    ("What is the total capacity of the Three Gorges Dam in megawatts?", "22,500 megawatts"),
    ("What is the exact height of the Willis Tower (Sears Tower) in meters?", "442 meters (527 meters with antenna)"),
    ("What is the total length of the Appalachian Trail in kilometers?", "approximately 3,524 kilometers (2,190 miles)"),
    ("What is the exact depth of the Dead Sea below sea level?", "approximately 430.5 meters below sea level"),
    ("What is the diameter of the Sun in kilometers?", "approximately 1,391,000 kilometers"),
    ("How many islands make up Indonesia?", "approximately 17,508 islands"),
    ("How many languages are spoken in India?", "approximately 780 languages (22 scheduled languages in the constitution)"),
    ("How many stations are in the London Underground?", "272 stations"),
    ("How many pyramids are there in Egypt?", "approximately 118-138 known pyramids"),
    ("How many characters are in the Chinese writing system?", "over 50,000 characters exist; approximately 8,000 in common use"),
    ("How many string quartets did Beethoven compose?", "16 string quartets"),
    ("How many plays did Shakespeare write?", "37 plays (commonly accepted count)"),
    ("How many cantatas did J.S. Bach compose?", "over 200 church cantatas survive (of approximately 300 composed)"),
    ("How many piano sonatas did Beethoven compose?", "32 piano sonatas"),
    ("How many novels did Charles Dickens write?", "15 novels"),
    ("In what year was the first successful kidney transplant performed?", "1954"),
    ("What year was the first programmable computer completed?", "1945 (ENIAC) or 1941 (Z3, by some definitions)"),
    ("In what year was insulin first used to treat diabetes?", "1922"),
    ("What year was the Periodic Table first published by Mendeleev?", "1869"),
    ("In what year was the first successful blood transfusion performed?", "1818 (human-to-human by James Blundell)"),
    ("What year was the Hubble Space Telescope launched?", "1990"),
    ("In what year was the first nuclear reactor achieved?", "1942 (Chicago Pile-1)"),
    ("What year was the transistor invented?", "1947"),
    ("In what year was the first successful airplane flight by the Wright Brothers?", "1903"),
    ("What year was the laser first demonstrated?", "1960"),
    ("What is the orbital period of Mercury around the Sun in Earth days?", "approximately 88 Earth days"),
    ("What is the surface temperature of the Sun in degrees Celsius?", "approximately 5,500 degrees Celsius"),
    ("What is the boiling point of helium in degrees Celsius?", "approximately -268.9 degrees Celsius"),
    ("What is the density of gold in grams per cubic centimeter?", "approximately 19.32 g/cm³"),
    ("What is the melting point of iron in degrees Celsius?", "approximately 1,538 degrees Celsius"),
    ("What is the half-life of uranium-238 in years?", "approximately 4.468 billion years"),
    ("What is the speed of light in water?", "approximately 225,000 kilometers per second"),
    ("What is the atomic mass of iron?", "approximately 55.845 u"),
    ("What is the electronegativity of fluorine on the Pauling scale?", "3.98"),
    ("What is the ionization energy of hydrogen in electron volts?", "approximately 13.6 eV"),
    ("What is the southernmost city in the world with a population over 100,000?", "Ushuaia, Argentina (or Punta Arenas, Chile)"),
    ("What is the largest lake in Africa by surface area?", "Lake Victoria (approximately 68,870 square kilometers)"),
    ("What is the highest volcano in Europe?", "Mount Elbrus at 5,642 meters (or Mount Etna at 3,357 meters if considering only Western Europe)"),
    ("What is the longest glacier in the world?", "Lambert Glacier in Antarctica (approximately 400 km long)"),
    ("What is the deepest gorge in the world?", "Yarlung Tsangpo Grand Canyon in Tibet (approximately 6,009 meters deep)"),
    ("What is the largest atoll in the world by land area?", "Kiritimati (Christmas Island) in Kiribati"),
    ("What is the highest navigable lake in the world?", "Lake Titicaca (approximately 3,812 meters above sea level)"),
    ("What is the most isolated city in the world?", "Perth, Australia (or Honolulu by some measures)"),
    ("What is the longest underwater tunnel in the world?", "Channel Tunnel at approximately 50.45 km (37.9 km underwater)"),
    ("What is the longest bridge in the world?", "Danyang-Kunshan Grand Bridge in China at approximately 164.8 km"),
    ("How many provinces does Spain have?", "50 provinces grouped into 17 autonomous communities"),
    ("How many states does India have?", "28 states and 8 union territories"),
    ("How many administrative regions does France have?", "18 regions (13 in metropolitan France, 5 overseas)"),
    ("How many oblasts does Russia have?", "46 oblasts (as of 2024)"),
    ("How many voivodeships does Poland have?", "16 voivodeships"),
    ("How many counties does England have?", "48 ceremonial counties"),
    ("How many regions does Italy have?", "20 regions"),
    ("How many federal states does Germany have?", "16 federal states (Bundesländer)"),
    ("How many departments does Colombia have?", "32 departments plus 1 capital district"),
    ("How many provinces does South Africa have?", "9 provinces"),
    ("What is the rarest naturally occurring element on Earth?", "Astatine"),
    ("What is the most expensive spice by weight?", "Saffron"),
    ("What is the world's oldest surviving republic?", "San Marino (founded 301 AD)"),
    ("What is the longest-running scientific experiment?", "The University of Queensland pitch drop experiment (started 1927)"),
    ("What is the world's largest flower by diameter?", "Rafflesia arnoldii (up to approximately 1 meter in diameter)"),
    ("What is the oldest known musical instrument?", "Bone flutes found in Germany (approximately 40,000 years old)"),
    ("What is the most venomous snake in the world?", "Inland taipan (Oxyuranus microlepidotus)"),
    ("What is the fastest fish in the ocean?", "Sailfish (approximately 110 km/h)"),
    ("What is the longest migration of any animal?", "Arctic tern (approximately 71,000 km round trip)"),
    ("What is the loudest animal in the world?", "Sperm whale (up to 230 decibels)"),
    ("What is the smallest flowering plant in the world?", "Wolffia (duckweed family, approximately 0.6 mm)"),
    ("What is the largest single organism on Earth by area?", "Honey fungus (Armillaria ostoyae) in Oregon, approximately 965 hectares"),
    ("How many chess grandmasters are there in the world?", "approximately 1,800 as of 2024"),
    ("What is the record for most Oscar nominations for a single film?", "14 nominations (All About Eve and Titanic tied; La La Land also received 14)"),
    ("What is the longest opera ever written?", "Die Meistersinger von Nürnberg by Wagner (approximately 4.5 hours)"),
    ("How many complete string quartets did Mozart compose?", "23 string quartets"),
    ("What is the record for most goals scored in a single FIFA World Cup tournament?", "Just Fontaine scored 13 goals in the 1958 World Cup"),
    ("How many test match centuries did Don Bradman score?", "29 centuries in 52 Tests"),
    ("What is the record for fastest goal in FIFA World Cup history?", "Hakan Sukur scored after 11 seconds (2002 World Cup)"),
    ("What is the world record for the longest tennis match?", "John Isner vs Nicolas Mahut at Wimbledon 2010 (11 hours 5 minutes)"),
    ("How many career home runs did Hank Aaron hit?", "755 career home runs"),
    ("How many Grand Slam titles has Novak Djokovic won?", "24 Grand Slam singles titles"),
    ("What is the oldest tennis tournament in the world?", "Wimbledon (first held in 1877)"),
    ("How many dots are on a pair of standard dice?", "42 dots total"),
    ("What is the oldest board game still played today?", "Go (approximately 2,500-4,000 years old)"),
    ("How many squares are on a standard chessboard?", "64 squares"),
    ("How many tiles are in a standard Scrabble set?", "100 tiles"),
    ("How many cards are in a standard tarot deck?", "78 cards"),
    ("What is the world's longest-running TV show?", "Guiding Light (1952-2009, 72 years if radio era included) or Coronation Street (1960-present)"),
    ("What is the deepest part of the Indian Ocean?", "Java Trench (Sunda Trench) at approximately 7,450 meters"),
    ("How many teeth does a great white shark have at any given time?", "approximately 300 teeth arranged in multiple rows"),
    ("What is the largest species of jellyfish?", "Lion's mane jellyfish (bell diameter up to 2.1 meters)"),
    ("How many hearts does an octopus have?", "3 hearts"),
    ("How many stomachs does a cow have?", "4 stomach compartments"),
    ("What is the wingspan of a wandering albatross?", "approximately 3.5 meters (largest wingspan of any living bird)"),
    ("How many neck vertebrae does a giraffe have?", "7 (same as most mammals)"),
    ("What is the gestation period of an African elephant?", "approximately 22 months"),
    ("How many known moons does Jupiter have?", "95 known moons (as of 2024)"),
    ("What is the rotation period of Venus in Earth days?", "approximately 243 Earth days (retrograde)"),
    ("How many keys does a standard computer keyboard have?", "104 keys (standard US layout)"),
]

# ---------------------------------------------------------------------------
# Category: BORDERLINE  (model might or might not want to verify)
# ---------------------------------------------------------------------------
BORDERLINE = [
    # --- Country populations ---
    ("What is the current population of Iceland?", "approximately 383,000"),
    ("What is the population of Liechtenstein?", "approximately 39,000"),
    ("What is the current population of Nigeria?", "approximately 230 million"),
    ("What is the population of Tokyo metropolitan area?", "approximately 37 million in the greater metropolitan area"),
    ("What is the current population of Bangladesh?", "approximately 170 million"),
    ("What is the population of Monaco?", "approximately 39,000"),
    ("What is the population of New Zealand?", "approximately 5.2 million"),
    ("What is the current population of Ethiopia?", "approximately 130 million"),
    ("What is the population of Singapore?", "approximately 5.9 million"),
    ("What is the population of Norway?", "approximately 5.5 million"),
    ("What is the population of Pakistan?", "approximately 240 million"),
    ("What is the population of the Netherlands?", "approximately 17.8 million"),
    ("What is the population of Taiwan?", "approximately 23.5 million"),
    ("What is the population of Sweden?", "approximately 10.5 million"),
    ("What is the population of Portugal?", "approximately 10.3 million"),
    ("What is the population of Cuba?", "approximately 11.2 million"),
    ("What is the population of Hungary?", "approximately 9.6 million"),
    ("What is the population of Bolivia?", "approximately 12.4 million"),
    ("What is the population of Serbia?", "approximately 6.6 million"),
    ("What is the population of Denmark?", "approximately 5.9 million"),
    ("What is the population of Finland?", "approximately 5.6 million"),
    ("What is the population of Slovakia?", "approximately 5.4 million"),
    ("What is the population of Costa Rica?", "approximately 5.2 million"),
    ("What is the population of Panama?", "approximately 4.5 million"),
    ("What is the population of Uruguay?", "approximately 3.4 million"),

    # --- Economic statistics ---
    ("What is the GDP of New Zealand?", "approximately $250 billion USD"),
    ("What is the current inflation rate in the United States?", "approximately 2.5-3% (varies by month)"),
    ("What is the current unemployment rate in Germany?", "approximately 5.7-6%"),
    ("How many billionaires are there in the world according to Forbes?", "approximately 2,780 (2024 list)"),
    ("What is the current exchange rate of 1 US dollar to Japanese yen?", "approximately 150-155 yen per dollar (fluctuates)"),
    ("What is the GDP per capita of Switzerland?", "approximately $100,000 USD"),
    ("What is the GDP of South Korea?", "approximately $1.7 trillion USD"),
    ("What is the national debt of the United States?", "approximately $34-35 trillion USD"),
    ("What is the GDP of Indonesia?", "approximately $1.4 trillion USD"),
    ("What is the GDP per capita of Norway?", "approximately $87,000 USD"),
    ("What is the current minimum wage in the United Kingdom?", "approximately £11.44 per hour (as of 2024)"),
    ("What is the GDP of Mexico?", "approximately $1.8 trillion USD"),
    ("What is the current unemployment rate in Japan?", "approximately 2.5%"),
    ("What is the GDP of Turkey?", "approximately $1.1 trillion USD"),
    ("What is the current unemployment rate in Spain?", "approximately 11-12%"),
    ("What is the GDP of Saudi Arabia?", "approximately $1.1 trillion USD"),
    ("What is the current inflation rate in the Eurozone?", "approximately 2-3%"),
    ("What is the GDP of Nigeria?", "approximately $475 billion USD"),
    ("What is the average household income in the United States?", "approximately $75,000 median household income"),
    ("What is the GDP of Poland?", "approximately $850 billion USD"),

    # --- Current leaders / figures ---
    ("Who is the current Secretary-General of the United Nations?", "Antonio Guterres"),
    ("Who is the current Prime Minister of Canada?", "Mark Carney (as of 2025)"),
    ("Who is the richest person in the world right now?", "Elon Musk (as of late 2024/early 2025)"),
    ("Who is the current Chancellor of Germany?", "Friedrich Merz (as of 2025)"),
    ("Who is the current President of France?", "Emmanuel Macron"),
    ("Who is the current Prime Minister of India?", "Narendra Modi"),
    ("Who is the current President of Brazil?", "Luiz Inacio Lula da Silva"),
    ("Who is the current President of South Korea?", "Yoon Suk-yeol"),
    ("Who is the current Prime Minister of Australia?", "Anthony Albanese"),
    ("Who is the current President of Mexico?", "Claudia Sheinbaum (took office October 2024)"),
    ("Who is the current Prime Minister of Japan?", "Shigeru Ishiba (as of late 2024)"),
    ("Who is the current King of the United Kingdom?", "King Charles III"),
    ("Who is the current Pope?", "Pope Leo XIV (as of 2025)"),
    ("Who is the CEO of Tesla?", "Elon Musk"),
    ("Who is the CEO of Amazon?", "Andy Jassy"),
    ("Who is the current Director-General of the World Health Organization?", "Tedros Adhanom Ghebreyesus"),
    ("Who is the current President of the European Commission?", "Ursula von der Leyen"),
    ("Who is the current Prime Minister of the United Kingdom?", "Keir Starmer"),
    ("Who is the current President of Indonesia?", "Prabowo Subianto (took office October 2024)"),
    ("Who is the current President of Turkey?", "Recep Tayyip Erdogan"),

    # --- Environmental / science stats ---
    ("What percentage of Earth's surface is covered by oceans?", "approximately 71%"),
    ("What is the current global average temperature anomaly compared to pre-industrial levels?", "approximately 1.2-1.5 degrees Celsius above pre-industrial levels"),
    ("How many active volcanoes are there in Indonesia?", "approximately 130 active volcanoes"),
    ("How many satellites are currently orbiting Earth?", "over 10,000 active satellites (as of 2024)"),
    ("What is the total length of the Amazon River?", "approximately 6,400 kilometers"),
    ("What percentage of the world's population lives in Asia?", "approximately 59%"),
    ("What is the current life expectancy in Japan?", "approximately 84 years"),
    ("How many nuclear power plants are operational in France?", "56 operational reactors at 18 sites"),
    ("What is the total number of languages spoken in Papua New Guinea?", "over 840 languages"),
    ("How many episodes of The Simpsons have been produced?", "over 770 episodes"),
    ("How many electric vehicles were sold worldwide in 2024?", "approximately 17 million"),
    ("What is the current world record for the men's 100m sprint?", "9.58 seconds by Usain Bolt (2009)"),
    ("How many countries are currently in the European Union?", "27 member states"),
    ("What percentage of the world's fresh water is in the Great Lakes?", "approximately 21% of the world's surface fresh water"),
    ("What is the average depth of the world's oceans?", "approximately 3,688 meters"),
    ("How many species of birds have been identified worldwide?", "approximately 10,000-11,000 species"),
    ("What is the current CO2 concentration in the atmosphere in parts per million?", "approximately 420-425 ppm"),
    ("What percentage of Earth's land surface is covered by forests?", "approximately 31%"),
    ("How many earthquakes of magnitude 7 or greater occur per year on average?", "approximately 15"),
    ("What is the average temperature on the surface of Venus?", "approximately 465 degrees Celsius"),

    # --- Technology / infrastructure stats ---
    ("How many daily active users does Instagram have?", "approximately 2 billion monthly active users"),
    ("How many websites exist on the internet?", "approximately 1.8-2 billion websites"),
    ("What percentage of the world's population has internet access?", "approximately 67%"),
    ("How many apps are available on the Apple App Store?", "approximately 1.8 million apps"),
    ("What is the total length of the US Interstate Highway System?", "approximately 78,465 kilometers (48,756 miles)"),
    ("How many airports are there in the United States?", "approximately 19,969 airports"),
    ("How many daily flights operate worldwide?", "approximately 100,000 flights per day"),
    ("What is the total length of railways in India?", "approximately 68,000 kilometers"),
    ("How many cell phone users are there worldwide?", "approximately 5.5 billion unique mobile subscribers"),
    ("What is the total length of China's high-speed rail network?", "approximately 45,000 kilometers"),

    # --- Cultural / demographic stats ---
    ("How many museums are there in the United States?", "approximately 35,000 museums"),
    ("What is the literacy rate in India?", "approximately 77%"),
    ("How many people speak Spanish as their first language worldwide?", "approximately 475 million native speakers"),
    ("What is the average life expectancy worldwide?", "approximately 73 years"),
    ("How many people practice Islam worldwide?", "approximately 1.9 billion"),
    ("What is the median age of the world's population?", "approximately 30.5 years"),
    ("How many international tourists travel per year globally?", "approximately 1.3 billion international tourist arrivals (2023)"),
    ("What is the literacy rate in the United States?", "approximately 88% (functional literacy)"),
    ("How many Olympic sports are there in the Summer Olympics?", "32 sports in the 2024 Paris Olympics"),
    ("How many countries participate in the Olympic Games?", "approximately 206 National Olympic Committees"),

    # --- Health / demographic stats ---
    ("What is the leading cause of death worldwide?", "Cardiovascular diseases (heart disease and stroke)"),
    ("How many organ transplants are performed worldwide each year?", "approximately 150,000"),
    ("What is the average height of an adult male in the United States?", "approximately 175.3 cm (5 feet 9 inches)"),
    ("What percentage of adults worldwide are classified as obese?", "approximately 16%"),
    ("How many people worldwide have diabetes?", "approximately 537 million adults"),
    ("What is the infant mortality rate in the United States?", "approximately 5.4 per 1,000 live births"),
    ("How many hospitals are there in the United States?", "approximately 6,100 hospitals"),
    ("What is the average number of calories an adult should consume per day?", "approximately 2,000-2,500 calories"),
    ("How many doctors are there per 1,000 people in Cuba?", "approximately 8.4 doctors per 1,000 people"),
    ("What is the life expectancy in South Korea?", "approximately 84 years"),

    # --- More borderline ---
    ("How many languages are spoken worldwide?", "approximately 7,000 languages"),
    ("What is the current world population?", "approximately 8.1 billion"),
    ("How many countries are there in the world?", "195 countries (193 UN member states plus 2 observer states)"),
    ("What is the tallest building in the world?", "Burj Khalifa at 828 meters"),
    ("What is the busiest airport in the world by passenger traffic?", "Hartsfield-Jackson Atlanta International Airport"),
    ("What is the longest highway in the world?", "Pan-American Highway at approximately 30,000 kilometers"),
    ("How many time zones are there in the world?", "24 standard time zones (though some use 30-minute or 45-minute offsets)"),
    ("What is the most visited country in the world by tourists?", "France (approximately 90 million international visitors per year)"),
    ("What is the most visited museum in the world?", "The Louvre in Paris"),
    ("How many people speak Hindi as a first language?", "approximately 345 million native speakers"),
    ("What is the largest city in the world by population?", "Tokyo (metropolitan area, approximately 37 million)"),
    ("What is the unemployment rate in South Africa?", "approximately 32-33%"),
    ("What is the average rainfall in the Amazon Rainforest?", "approximately 2,300 mm per year"),
    ("How many Nobel Prizes have been awarded in total?", "over 960 Nobel Prizes to individuals and organizations"),
    ("What is the largest hydroelectric dam in the world by capacity?", "Three Gorges Dam in China at approximately 22,500 MW"),
    ("How many UNESCO Intangible Cultural Heritage items are there?", "over 730 elements inscribed"),
    ("What is the deepest mine in the world?", "Mponeng Gold Mine in South Africa at approximately 4 km deep"),
    ("How many people worldwide lack access to clean drinking water?", "approximately 2.2 billion people"),
    ("What is the total renewable energy capacity worldwide?", "approximately 3,870 GW as of 2023"),
    ("What percentage of global electricity comes from renewable sources?", "approximately 30%"),
    # --- More borderline (115 more) ---
    ("What is the population of Ireland?", "approximately 5.1 million"),
    ("What is the population of Croatia?", "approximately 3.9 million"),
    ("What is the population of Lithuania?", "approximately 2.8 million"),
    ("What is the population of Slovenia?", "approximately 2.1 million"),
    ("What is the population of Latvia?", "approximately 1.8 million"),
    ("What is the population of Estonia?", "approximately 1.3 million"),
    ("What is the population of Cyprus?", "approximately 1.3 million"),
    ("What is the population of Luxembourg?", "approximately 660,000"),
    ("What is the population of Malta?", "approximately 530,000"),
    ("What is the population of Bhutan?", "approximately 780,000"),
    ("What is the population of Brunei?", "approximately 450,000"),
    ("What is the population of Fiji?", "approximately 930,000"),
    ("What is the population of Maldives?", "approximately 520,000"),
    ("What is the population of Suriname?", "approximately 620,000"),
    ("What is the population of Guyana?", "approximately 810,000"),
    ("What is the GDP of Vietnam?", "approximately $430 billion USD"),
    ("What is the GDP of Thailand?", "approximately $530 billion USD"),
    ("What is the GDP of the Philippines?", "approximately $440 billion USD"),
    ("What is the GDP of Colombia?", "approximately $380 billion USD"),
    ("What is the GDP of Chile?", "approximately $340 billion USD"),
    ("What is the GDP of Bangladesh?", "approximately $460 billion USD"),
    ("What is the GDP of Egypt?", "approximately $400 billion USD"),
    ("What is the GDP of Finland?", "approximately $300 billion USD"),
    ("What is the GDP of Portugal?", "approximately $290 billion USD"),
    ("What is the GDP of Czech Republic?", "approximately $330 billion USD"),
    ("Who is the current President of Argentina?", "Javier Milei"),
    ("Who is the current President of the Philippines?", "Ferdinand Marcos Jr."),
    ("Who is the current President of Egypt?", "Abdel Fattah el-Sisi"),
    ("Who is the current President of Nigeria?", "Bola Tinubu"),
    ("Who is the current Prime Minister of New Zealand?", "Christopher Luxon"),
    ("Who is the current Prime Minister of Italy?", "Giorgia Meloni"),
    ("Who is the current President of Colombia?", "Gustavo Petro"),
    ("Who is the current Prime Minister of Spain?", "Pedro Sanchez"),
    ("Who is the current President of Chile?", "Gabriel Boric"),
    ("Who is the current Prime Minister of Thailand?", "Paetongtarn Shinawatra (as of 2024)"),
    ("What is the current life expectancy in the United States?", "approximately 77-78 years"),
    ("What is the current life expectancy in South Korea?", "approximately 84 years"),
    ("What is the current life expectancy in India?", "approximately 70 years"),
    ("What is the current life expectancy in Nigeria?", "approximately 53 years"),
    ("What is the current life expectancy in Brazil?", "approximately 76 years"),
    ("What is the literacy rate in China?", "approximately 97%"),
    ("What is the literacy rate in Brazil?", "approximately 94%"),
    ("What is the literacy rate in Nigeria?", "approximately 62%"),
    ("What is the literacy rate in Japan?", "approximately 99%"),
    ("What is the literacy rate in Pakistan?", "approximately 58%"),
    ("How many daily active users does YouTube have?", "approximately 2.5 billion monthly active users"),
    ("How many daily active users does TikTok have?", "approximately 1.5 billion monthly active users"),
    ("How many daily active users does Facebook have?", "approximately 2.1 billion daily active users"),
    ("How many daily active users does WhatsApp have?", "approximately 2 billion monthly active users"),
    ("How many subscribers does Netflix have worldwide?", "approximately 280-300 million paid subscribers"),
    ("What percentage of global energy comes from fossil fuels?", "approximately 80%"),
    ("What percentage of global energy comes from nuclear power?", "approximately 10% of global electricity"),
    ("How many nuclear power plants are there worldwide?", "approximately 440 operational reactors"),
    ("What is the average annual rainfall in London?", "approximately 600 mm (23.6 inches)"),
    ("What is the average annual temperature in Moscow?", "approximately 5.8 degrees Celsius"),
    ("How many species of mammals have been identified worldwide?", "approximately 6,400 species"),
    ("How many species of fish have been identified worldwide?", "approximately 35,000 species"),
    ("How many species of reptiles have been identified worldwide?", "approximately 12,000 species"),
    ("How many species of insects have been identified worldwide?", "approximately 1 million described species"),
    ("What is the total area of the Amazon Rainforest?", "approximately 5.5 million square kilometers"),
    ("What is the total area of the Arctic ice sheet?", "varies seasonally; minimum approximately 4-5 million square kilometers in summer"),
    ("How many dams are there in the world?", "approximately 58,000 large dams"),
    ("How many commercial airports are there worldwide?", "approximately 17,000"),
    ("What is the total global military spending per year?", "approximately $2.4 trillion USD (2023)"),
    ("How many active military personnel does the United States have?", "approximately 1.3 million active duty"),
    ("How many active military personnel does China have?", "approximately 2 million active duty"),
    ("What is the total foreign aid budget of the United States?", "approximately $50-60 billion per year"),
    ("How many refugees are there worldwide?", "approximately 110 million forcibly displaced people (2023)"),
    ("What is the global adult literacy rate?", "approximately 87%"),
    ("What percentage of the world's population lives in urban areas?", "approximately 56%"),
    ("How many children worldwide are out of school?", "approximately 250 million"),
    ("What is the average global fertility rate?", "approximately 2.3 births per woman"),
    ("What percentage of the global population is under 18?", "approximately 30%"),
    ("How many people worldwide are affected by hunger?", "approximately 735 million (2023)"),
    ("What is the current price of a barrel of Brent crude oil?", "approximately $70-80 (fluctuates)"),
    ("What is the current value of global trade per year?", "approximately $25 trillion USD"),
    ("How many container ships are operating worldwide?", "approximately 5,500 container ships"),
    ("What is the total length of undersea internet cables worldwide?", "approximately 1.3 million kilometers"),
    ("How many data centers exist worldwide?", "approximately 8,000-10,000 large data centers"),
    ("What is the total global carbon emissions from aviation?", "approximately 2.5% of global CO2 emissions"),
    ("How many people die from air pollution worldwide each year?", "approximately 7 million (WHO estimate)"),
    ("What is the total area of coral reefs worldwide?", "approximately 284,300 square kilometers"),
    ("How many plant species are considered threatened with extinction?", "approximately 40% of plant species"),
    ("How many national languages does India recognize in its constitution?", "22 scheduled languages"),
    ("How many UNESCO biosphere reserves are there worldwide?", "over 740 biosphere reserves in 134 countries"),
    ("What is the total area of Antarctica?", "approximately 14 million square kilometers"),
    ("What is the average salary in the United States?", "approximately $60,000 median annual salary"),
    ("What is the average salary in Switzerland?", "approximately $85,000-95,000 median annual salary"),
    ("What is the average rent for a one-bedroom apartment in New York City?", "approximately $3,500-4,000 per month"),
    ("What is the average rent for a one-bedroom apartment in London?", "approximately £1,800-2,200 per month"),
    ("How many billionaires does the United States have?", "approximately 735 (Forbes 2024)"),
    ("How many billionaires does China have?", "approximately 500 (Forbes 2024)"),
    ("What is the Gini coefficient of the United States?", "approximately 0.39"),
    ("What percentage of global wealth is held by the top 1%?", "approximately 45%"),
    ("How many Fortune 500 companies are headquartered in New York?", "approximately 50-55"),
    ("What is the total value of the global stock market?", "approximately $110 trillion"),
    ("How many breweries are there in the United States?", "approximately 9,500"),
    ("How many Michelin-starred restaurants are there worldwide?", "approximately 3,500"),
    ("How many marathon runners complete a marathon worldwide each year?", "approximately 1.1 million"),
    ("How many people climb Mount Everest each year?", "approximately 500-800 summits per year"),
    ("How many visitors does the Eiffel Tower receive per year?", "approximately 7 million visitors"),
    ("How many visitors does the Taj Mahal receive per year?", "approximately 7-8 million visitors"),
    ("What is the busiest port in the world by container volume?", "Port of Shanghai"),
    ("What is the longest commercial flight route in the world?", "Singapore Airlines Singapore to New York (approximately 15,349 km)"),
    ("How many passenger trains operate daily in Japan?", "approximately 30,000 trains per day on the JR network"),
    ("How many people use public transit daily in New York City?", "approximately 5-6 million riders per weekday"),
    ("What is the largest solar power plant in the world?", "Bhadla Solar Park in India (approximately 2,245 MW)"),
    ("What is the largest wind farm in the world?", "Gansu Wind Farm in China (approximately 20,000 MW planned capacity)"),
    ("How many electric vehicle charging stations are there in the United States?", "approximately 170,000 public charging ports"),
    ("What percentage of new cars sold in Norway are electric?", "approximately 80-90% battery electric"),
    ("How many Tesla vehicles have been sold worldwide?", "over 6 million cumulative as of 2024"),
    ("What is the total installed nuclear capacity worldwide?", "approximately 440 GW"),
    ("How many PhDs are awarded annually in the United States?", "approximately 55,000-60,000 per year"),
    ("What is the average cost of a college degree in the United States?", "approximately $100,000-$150,000 for a four-year degree (varies widely)"),
    ("How many public libraries are there in the United States?", "approximately 17,000 public library systems"),
]

# ---------------------------------------------------------------------------
# Category: TEMPORAL  (time-sensitive — model SHOULD need search)
# ---------------------------------------------------------------------------
TEMPORAL = [
    # --- Sports results ---
    ("Who won the 2025 Super Bowl?", "Philadelphia Eagles (Super Bowl LIX, February 2025)"),
    ("Who won the 2025 Australian Open men's singles title?", "Jannik Sinner"),
    ("Who won the 2025 Australian Open women's singles title?", "Madison Keys"),
    ("Who won the 2024 Ballon d'Or award?", "Rodri (Rodrigo Hernandez, Manchester City)"),
    ("Who won the 2024 Copa America?", "Argentina"),
    ("Which team won the 2024 NBA Championship?", "Boston Celtics"),
    ("Which country hosted the 2025 FIFA Club World Cup?", "United States (summer 2025)"),
    ("Who won the 2024 UEFA European Championship (Euro 2024)?", "Spain"),
    ("Who won the 2024 MLB World Series?", "Los Angeles Dodgers"),
    ("Who won the 2024 Tour de France?", "Tadej Pogacar"),
    ("Who won the 2024 French Open men's singles?", "Carlos Alcaraz"),
    ("Who won the 2024 Wimbledon men's singles?", "Carlos Alcaraz"),
    ("Who won the 2024 US Open men's singles?", "Jannik Sinner"),
    ("Who won the 2024 Formula 1 World Drivers' Championship?", "Max Verstappen"),
    ("Who won the 2024 Stanley Cup?", "Florida Panthers"),
    ("Who won the 2024 Cricket T20 World Cup?", "India"),
    ("Who won the 2024 Olympic Games men's 100m gold medal?", "Noah Lyles"),
    ("Who won the 2024 Olympic Games women's gymnastics all-around gold?", "Simone Biles"),
    ("Where were the 2024 Summer Olympics held?", "Paris, France"),
    ("Who won the 2024 Cy Young Award in the American League?", "Tarik Skubal"),
    ("Who won the 2024 NFL MVP award?", "Lamar Jackson"),
    ("Who won the 2024 PGA Championship?", "Xander Schauffele"),
    ("Which team won the 2024 MLS Cup?", "LA Galaxy"),
    ("Who won the 2024 UFC heavyweight championship fight (Jones vs Miocic)?", "Jon Jones"),
    ("Who won the 2024 Heisman Trophy?", "Travis Hunter"),
    ("Who won the 2024 WNBA Championship?", "New York Liberty"),
    ("Who won the 2024 Rugby Championship?", "South Africa"),
    ("Who won the 2024 Indy 500?", "Josef Newgarden"),
    ("Who won the 2024-25 English Premier League (as of early 2025)?", "Season still in progress as of early 2025; Liverpool leading"),
    ("Who won the 2024 Champions League final?", "Real Madrid"),

    # --- Political events ---
    ("Who won the 2024 US Presidential Election?", "Donald Trump"),
    ("What was the outcome of the 2024 UK general election?", "Labour Party won a landslide victory; Keir Starmer became Prime Minister"),
    ("What were the results of the 2024 European Parliament elections?", "EPP remained the largest group; shift toward right-wing parties"),
    ("Who became the new NATO Secretary General in 2024?", "Mark Rutte (took office October 2024)"),
    ("What new country joined BRICS in 2024?", "Egypt, Ethiopia, Iran, Saudi Arabia, and UAE were invited; most joined in January 2024"),
    ("Who won the 2024 Taiwan presidential election?", "Lai Ching-te (William Lai) of the DPP"),
    ("Who won the 2024 Indonesian presidential election?", "Prabowo Subianto"),
    ("Who won the 2024 Indian general election?", "BJP-led NDA coalition; Narendra Modi re-elected as PM"),
    ("Who won the 2024 South African general election?", "ANC won but lost majority; formed coalition government"),
    ("Who won the 2024 Venezuelan presidential election?", "Nicolas Maduro (disputed; opposition claimed Edmundo Gonzalez won)"),
    ("Who became the new Prime Minister of Japan in late 2024?", "Shigeru Ishiba"),
    ("Who won the 2024 Mexican presidential election?", "Claudia Sheinbaum"),
    ("Who won the 2024 Uruguayan presidential election?", "Yamandu Orsi"),
    ("What country joined NATO most recently?", "Sweden (joined in March 2024)"),
    ("Who won the 2024 Sri Lankan presidential election?", "Anura Kumara Dissanayake"),
    ("Who won the 2024 Senegalese presidential election?", "Bassirou Diomaye Faye"),
    ("Who became President of the European Council in late 2024?", "Antonio Costa"),
    ("What major trade agreement was signed or updated in 2024?", "African Continental Free Trade Area (AfCFTA) continued implementation"),
    ("Which US state held a significant ballot initiative on abortion rights in 2024?", "Multiple states including Florida, Arizona, and others; results varied"),
    ("Who is the current US Vice President as of 2025?", "JD Vance"),

    # --- Awards / prizes ---
    ("Who won the 2024 Nobel Prize in Physics?", "John Hopfield and Geoffrey Hinton for foundational discoveries in machine learning"),
    ("Who won the 2024 Nobel Prize in Literature?", "Han Kang"),
    ("Who won the 2024 Nobel Prize in Chemistry?", "David Baker, Demis Hassabis, and John Jumper for protein structure prediction"),
    ("Who won the 2024 Nobel Peace Prize?", "Nihon Hidankyo (Japanese atomic bomb survivors organization)"),
    ("Who won the 2024 Nobel Prize in Economics?", "Daron Acemoglu, Simon Johnson, and James Robinson"),
    ("Who won the 2024 Nobel Prize in Physiology or Medicine?", "Victor Ambros and Gary Ruvkun for discovery of microRNA"),
    ("What won Best Picture at the 2024 Academy Awards?", "Oppenheimer"),
    ("Who won the 2024 Booker Prize?", "Samantha Harvey for 'Orbital'"),
    ("Who won the 2024 Pulitzer Prize for Fiction?", "Jayne Anne Phillips for 'Night Watch'"),
    ("What won the 2024 Hugo Award for Best Novel?", "Some Desperate Glory by Emily Tesh"),
    ("Who won the 2024 Fields Medal?", "Fields Medal is awarded every 4 years; not awarded in 2024 (last in 2022, next in 2026)"),
    ("Who won the 2024 Grammy Award for Album of the Year?", "Taylor Swift for 'Midnights'"),
    ("Who won the 2024 Golden Globe for Best Motion Picture Drama?", "Oppenheimer"),
    ("What won the Palme d'Or at the 2024 Cannes Film Festival?", "Anora by Sean Baker"),
    ("Who won the 2024 Man Booker International Prize?", "Jenny Erpenbeck for 'Kairos'"),
    ("Who won the 2024 Abel Prize in Mathematics?", "Michel Talagrand"),
    ("Who won the 2024 Turing Award?", "Andrew Barto and Richard Sutton for reinforcement learning (announced 2025)"),
    ("Who won the 2024 Pritzker Architecture Prize?", "Riken Yamamoto"),
    ("What film won the Golden Lion at the 2024 Venice Film Festival?", "The Room Next Door by Pedro Almodovar"),
    ("Who won the 2024 World Food Prize?", "Geoffrey Hawtin for conserving crop diversity"),

    # --- Business / tech news ---
    ("What is the current price of Bitcoin in US dollars?", "fluctuates; approximately $90,000-$100,000 range in early 2025"),
    ("What was the closing value of the S&P 500 at the end of 2024?", "approximately 5,881 (December 31, 2024)"),
    ("What is the current federal funds rate set by the US Federal Reserve?", "approximately 4.25-4.5% (as of early 2025)"),
    ("Who is the current CEO of OpenAI?", "Sam Altman"),
    ("What AI model did Google DeepMind release in late 2024?", "Gemini 2.0"),
    ("What was the latest version of Python released in 2025?", "Python 3.13.x (check for latest patch version)"),
    ("What major social media platform rebranded to 'X' in 2023?", "Twitter rebranded to X"),
    ("What was Apple's latest iPhone model released in 2024?", "iPhone 16 series (iPhone 16, 16 Plus, 16 Pro, 16 Pro Max)"),
    ("What was the market capitalization of Apple in early 2025?", "approximately $3.5-3.7 trillion"),
    ("What was the market capitalization of Nvidia in early 2025?", "approximately $3.0-3.5 trillion"),
    ("When did OpenAI release GPT-4o?", "May 2024"),
    ("What major tech company laid off the most employees in 2024?", "Multiple companies including Intel, Dell, and others had significant layoffs"),
    ("What was the IPO price of Reddit when it went public?", "Reddit IPO'd in March 2024 at $34 per share"),
    ("What was the valuation of SpaceX in late 2024?", "approximately $210-350 billion"),
    ("What was Microsoft's revenue in fiscal year 2024?", "approximately $245 billion"),
    ("What new AI model did Anthropic release in 2024?", "Claude 3.5 Sonnet and Claude 3.5 Haiku"),
    ("What was the price of gold per ounce in early 2025?", "approximately $2,700-2,800 per troy ounce"),
    ("What was TSMC's revenue in 2024?", "approximately $90 billion USD"),
    ("What was the largest IPO of 2024?", "Lineage Inc. (cold storage REIT, approximately $5.1 billion)"),
    ("What was the average price of a US home in 2024?", "approximately $420,000 median home price"),

    # --- Science / space achievements ---
    ("Which spacecraft successfully landed on the Moon's south pole region in 2023?", "India's Chandrayaan-3 (Vikram lander)"),
    ("What was the date of the total solar eclipse visible across North America in 2024?", "April 8, 2024"),
    ("What was the world population estimate as of January 2025?", "approximately 8.1 billion"),
    ("What major space mission launched in 2024?", "Europa Clipper (NASA, launched October 2024)"),
    ("What was the Artemis program's latest milestone?", "Artemis II crew announced; mission planned for 2025"),
    ("What significant climate milestone was reached in 2024?", "2024 was confirmed as the hottest year on record; first full year above 1.5°C anomaly"),
    ("What new element or particle was discovered or confirmed in 2024?", "No new elements; continued research in particle physics at CERN"),
    ("What breakthrough in nuclear fusion was announced in 2024?", "Continued progress at NIF and ITER; multiple private fusion companies reached milestones"),
    ("What private company successfully landed on the Moon in 2024?", "Intuitive Machines' Odysseus lander (IM-1 mission, February 2024, partial success)"),
    ("What was the latest Mars mission update in 2024?", "Perseverance rover continued sample caching; Mars Sample Return mission restructured"),
    ("What astronomical event was notable in 2024?", "Comet Tsuchinshan-ATLAS became visible to the naked eye in October 2024"),
    ("What was the highest-resolution image of the Sun taken as of 2024?", "Daniel K. Inouye Solar Telescope continued to produce the highest-resolution solar images"),
    ("When did the JWST capture the deepest infrared image of the universe?", "First deep field image released July 2022; continued deeper observations through 2024"),
    ("What gene therapy was approved by the FDA in 2024?", "Multiple gene therapies including Casgevy (for sickle cell disease, approved late 2023/early 2024)"),
    ("What was the most significant earthquake in 2024?", "January 1, 2024 Noto earthquake in Japan (magnitude 7.6)"),

    # --- International affairs / events ---
    ("What was the global box office gross for the highest-grossing film of 2025?", "varies depending on time of query; check current box office data"),
    ("What major international summit was held in 2024?", "COP29 held in Baku, Azerbaijan in November 2024"),
    ("What country experienced a major political crisis in 2024?", "Bangladesh (Sheikh Hasina ousted in August 2024); also South Korea (Yoon martial law crisis)"),
    ("What was the status of the Russia-Ukraine conflict as of early 2025?", "Ongoing; negotiations remained stalled as of early 2025"),
    ("What was the status of the Israel-Hamas conflict as of early 2025?", "Ceasefire deal reached in January 2025"),
    ("What was the outcome of the 2024 COP29 climate summit?", "Agreement reached on climate finance; pledged $300 billion per year for developing nations"),
    ("What major natural disaster occurred in early 2024?", "January 1, 2024 Noto earthquake in Japan; also severe flooding in multiple countries"),
    ("What country applied to join the European Union in 2024?", "Ukraine and Moldova had candidate status; Georgia's candidacy was complicated by political issues"),
    ("Which airline had a major safety incident in early 2024?", "Alaska Airlines (Boeing 737 MAX 9 door plug blowout, January 2024)"),
    ("What major bridge or infrastructure collapsed in 2024?", "Francis Scott Key Bridge in Baltimore (March 2024)"),

    # --- Entertainment / culture ---
    ("What was the highest-grossing film of 2024?", "Inside Out 2"),
    ("What was the most-streamed song on Spotify in 2024?", "Varies by timeframe; 'Espresso' by Sabrina Carpenter was among the top"),
    ("What major music artist announced a world tour in 2024-2025?", "Multiple artists including Oasis reunion tour announcement"),
    ("What was the most-watched TV series on Netflix in 2024?", "Multiple contenders including 'Squid Game' Season 2"),
    ("What video game won Game of the Year at The Game Awards 2024?", "Astro Bot"),
    ("What major music festival incident occurred in 2024?", "Various festival events; no single dominant incident"),
    ("What was Taylor Swift's latest album released in 2024?", "The Tortured Poets Department (April 2024)"),
    ("What was Beyonce's major tour in 2024?", "Renaissance World Tour concluded; Cowboy Carter album released"),
    ("What was the most-watched event on television in 2024?", "Super Bowl LVIII (Chiefs vs. 49ers)"),
    ("What major streaming service launched or merged in 2024?", "Various mergers; Paramount+ and Skydance merger announced"),

    # --- More temporal ---
    ("What was the US GDP growth rate in 2024?", "approximately 2.8% annual growth"),
    ("What was the average price of gasoline in the US in 2024?", "approximately $3.30-3.50 per gallon"),
    ("How many immigrants crossed the US-Mexico border in 2024?", "Numbers decreased from 2023 highs; exact figures varied by source"),
    ("What was the global CO2 emissions level in 2024?", "approximately 37.4 billion tonnes of CO2"),
    ("What was the unemployment rate in the United States in early 2025?", "approximately 4.0-4.2%"),
    ("What was the most significant cyberattack of 2024?", "Multiple significant incidents including Change Healthcare breach"),
    ("What AI regulation was passed in 2024?", "EU AI Act entered into force in August 2024"),
    ("What country legalized same-sex marriage in 2024?", "Thailand legalized same-sex marriage (effective January 2025)"),
    ("What was the most significant volcanic eruption of 2024?", "Multiple eruptions including in Iceland (Reykjanes Peninsula)"),
    ("What was the global smartphone market share leader in 2024?", "Samsung and Apple competed for the top spot; Samsung slightly ahead overall"),
    ("What major cryptocurrency regulation was passed in 2024?", "US approved spot Bitcoin ETFs in January 2024"),
    ("What was the price of a barrel of Brent crude oil in early 2025?", "approximately $70-80 per barrel"),
    ("What new country was admitted to the United Nations in 2024?", "No new members admitted in 2024"),
    ("What major dam or reservoir reached critical levels in 2024?", "Various drought-affected reservoirs; conditions varied by region"),
    ("What was the most significant aviation milestone of 2024?", "Boeing faced increased scrutiny after Alaska Airlines door plug incident"),
    ("What new space station module was launched in 2024?", "China's Tiangong station continued operations; ISS deorbit planning advanced"),
    ("What major tech antitrust ruling was made in 2024?", "US DOJ ruled Google maintained an illegal monopoly in search"),
    ("What was the world's most valuable company by market cap in early 2025?", "Apple (approximately $3.5-3.7 trillion)"),
    ("How many people worldwide used ChatGPT as of early 2025?", "over 200 million weekly active users"),
    ("What was the most downloaded mobile app worldwide in 2024?", "TikTok remained among the most downloaded apps globally"),
    # --- More temporal (105 more) ---
    ("Who won the 2024 Olympic Games men's marathon gold medal?", "Tamirat Tola of Ethiopia"),
    ("Who won the 2024 Olympic Games women's 100m gold medal?", "Julien Alfred of Saint Lucia"),
    ("Who won the 2024 Olympic Games men's swimming 100m freestyle?", "Pan Zhanle of China"),
    ("Who won the 2024 Olympic Games men's basketball gold medal?", "United States"),
    ("Who won the 2024 Olympic Games women's soccer gold medal?", "United States"),
    ("How many gold medals did the United States win at the 2024 Paris Olympics?", "40 gold medals"),
    ("How many total medals did China win at the 2024 Paris Olympics?", "91 total medals (40 gold)"),
    ("Who won the 2024 Daytona 500?", "William Byron"),
    ("Who won the 2024 Masters golf tournament?", "Scottie Scheffler"),
    ("Who won the 2024 US Open golf tournament?", "Bryson DeChambeau"),
    ("Who won the 2024 Open Championship (British Open) golf?", "Xander Schauffele"),
    ("Who won the 2023 FIFA Women's World Cup?", "Spain"),
    ("Who won the 2024 Super Bowl (LVIII)?", "Kansas City Chiefs"),
    ("Who won the 2024 College Football Playoff National Championship?", "Michigan Wolverines"),
    ("Who won the 2024 March Madness (NCAA men's basketball)?", "UConn Huskies"),
    ("Who won the 2024 French Open women's singles?", "Iga Swiatek"),
    ("Who won the 2024 Wimbledon women's singles?", "Barbora Krejcikova"),
    ("Who won the 2024 US Open women's singles?", "Aryna Sabalenka"),
    ("Who won the 2024 NASCAR Cup Series championship?", "Joey Logano"),
    ("Who won the 2024 Ryder Cup?", "Europe won the 2023 Ryder Cup (no Ryder Cup in 2024; next is 2025)"),
    ("Who won the 2024 Indian Premier League (IPL)?", "Kolkata Knight Riders"),
    ("Who won the 2024 Rugby World Cup?", "South Africa won the 2023 Rugby World Cup (no RWC in 2024)"),
    ("Who won the 2024 ATP Finals?", "Jannik Sinner"),
    ("Who won the 2024 WTA Finals?", "Coco Gauff"),
    ("Who won the 2024 Boston Marathon men's race?", "Sisay Lemma"),
    ("Who won the 2024 Boston Marathon women's race?", "Hellen Obiri"),
    ("Who won the 2024 London Marathon men's race?", "Alexander Mutiso"),
    ("Who won the 2024 New York City Marathon men's race?", "Tamirat Tola"),
    ("Who won the 2024 Monaco Grand Prix in Formula 1?", "Charles Leclerc"),
    ("Who won the 2024 Le Mans 24 Hours?", "Ferrari (499P)"),
    ("Who won the 2024 South Korean presidential impeachment vote?", "Yoon Suk-yeol was impeached by parliament in December 2024"),
    ("What was the outcome of the 2024 Bangladesh political crisis?", "Sheikh Hasina resigned and fled; interim government led by Muhammad Yunus"),
    ("Who won the 2024 Austrian parliamentary election?", "FPÖ won the most votes; coalition negotiations followed"),
    ("Who won the 2024 Romanian presidential election?", "Nicuşor Dan (after controversial first round that was annulled)"),
    ("What major political event happened in Syria in late 2024?", "Assad regime fell; rebel forces took Damascus in December 2024"),
    ("Who became the new Chancellor of Germany in 2025?", "Friedrich Merz (after February 2025 election)"),
    ("What happened in the 2024 Georgia (country) parliamentary election?", "Georgian Dream party claimed victory; opposition alleged fraud; mass protests"),
    ("Who won the 2024 Moldovan presidential election?", "Maia Sandu won re-election"),
    ("What significant event happened at COP29 in Baku?", "$300 billion per year climate finance pledge for developing nations"),
    ("What political crisis occurred in South Korea in December 2024?", "President Yoon declared martial law briefly; was later impeached"),
    ("Who won the 2024 Nobel Prize in Economic Sciences?", "Daron Acemoglu, Simon Johnson, and James Robinson"),
    ("Who won the 2024 Pritzker Prize?", "Riken Yamamoto"),
    ("Who won the 2024 Wolf Prize in Mathematics?", "Noga Alon"),
    ("What film won the BAFTA for Best Film in 2024?", "Oppenheimer"),
    ("Who won the 2024 Emmy Award for Outstanding Drama Series?", "Shōgun"),
    ("Who won the 2024 Emmy Award for Outstanding Comedy Series?", "Hacks"),
    ("Who won the 2024 Tony Award for Best Musical?", "The Outsiders"),
    ("Who won the 2024 Mercury Prize?", "English Teacher for 'This Could Be Texas'"),
    ("Who won the 2024 Turner Prize?", "Jasleen Kaur"),
    ("Who won the 2024 International Booker Prize?", "Jenny Erpenbeck for 'Kairos' (translated by Michael Hofmann)"),
    ("What was Samsung's latest flagship phone released in 2024?", "Samsung Galaxy S24 Ultra"),
    ("What was Google's latest Pixel phone released in 2024?", "Google Pixel 9 series"),
    ("When did Meta release Llama 3?", "April 2024 (Llama 3), July 2024 (Llama 3.1)"),
    ("What was the latest major Windows update in 2024?", "Windows 11 24H2"),
    ("What new gaming console was announced or released in 2024?", "Nintendo announced the Switch successor; PlayStation 5 Pro released"),
    ("What was the latest major Unity engine version in 2024?", "Unity 6 (released 2024)"),
    ("What was Spotify's total subscriber count in 2024?", "approximately 640 million users (240 million premium subscribers)"),
    ("What was the largest tech acquisition of 2024?", "Synopsys acquisition of Ansys for approximately $35 billion (announced)"),
    ("What cryptocurrency ETF was approved in the US in 2024?", "Spot Bitcoin ETFs approved in January 2024; Spot Ethereum ETFs approved in July 2024"),
    ("What was the biggest data breach of 2024?", "National Public Data breach (2.9 billion records); Change Healthcare breach"),
    ("What was the stock price of Nvidia at the end of 2024?", "approximately $130-140 per share (post-split)"),
    ("What was OpenAI's valuation in late 2024?", "approximately $157 billion"),
    ("What new telescope or observatory began operations in 2024?", "Vera C. Rubin Observatory neared completion; various JWST discoveries continued"),
    ("What was the latest SpaceX Starship test flight result?", "Multiple test flights in 2024; booster catch achieved on Flight 5 (October 2024)"),
    ("What was the latest Blue Origin launch milestone?", "New Glenn first launch attempt in early 2025"),
    ("What was China's latest space achievement in 2024?", "Chang'e 6 successfully returned samples from the far side of the Moon"),
    ("What was the latest discovery by the James Webb Space Telescope?", "Multiple discoveries including early galaxy observations and exoplanet atmosphere analysis throughout 2024"),
    ("What significant medical breakthrough occurred in 2024?", "First pig kidney transplant into a living human (March 2024)"),
    ("What was the status of bird flu (H5N1) in 2024?", "Spread to US dairy cattle; limited human cases; increased surveillance"),
    ("What major drug was approved by the FDA in 2024?", "Multiple approvals including donanemab for Alzheimer's"),
    ("What was the global average temperature in 2024?", "2024 was the hottest year on record; approximately 1.5°C above pre-industrial levels"),
    ("What major hurricane hit the United States in 2024?", "Hurricane Helene (September) and Hurricane Milton (October) hit Florida/Southeast US"),
    ("What major wildfire event occurred in 2024?", "Multiple significant wildfires including in Canada and the western United States"),
    ("What major flooding event occurred in 2024?", "Severe flooding in Spain (Valencia region, October 2024); also flooding in Brazil, Kenya, and others"),
    ("What was the highest-grossing film of 2024 worldwide?", "Inside Out 2 (approximately $1.7 billion worldwide)"),
    ("What was the second highest-grossing film of 2024?", "Deadpool & Wolverine (approximately $1.3 billion worldwide)"),
    ("What new Disney/Pixar film was released in 2024?", "Inside Out 2"),
    ("What major music artist died in 2024?", "Several notable losses; no single dominant figure"),
    ("What was the biggest concert tour of 2024?", "Taylor Swift's Eras Tour (continued from 2023; highest-grossing tour ever)"),
    ("What new album did Billie Eilish release in 2024?", "HIT ME HARD AND SOFT (May 2024)"),
    ("What new album did Kendrick Lamar release in 2024?", "GNX (November 2024)"),
    ("What was the most-streamed artist on Spotify in 2024?", "Taylor Swift"),
    ("What new streaming series was the most popular on Disney+ in 2024?", "Multiple popular releases including Shōgun (on Hulu/FX)"),
    ("What was the Game of the Year winner at The Game Awards 2023?", "Baldur's Gate 3"),
    ("What major video game was released in early 2024?", "Palworld, Helldivers 2, Final Fantasy VII Rebirth"),
    ("What major video game was released in late 2024?", "Multiple releases including Indiana Jones and the Great Circle, Astro Bot"),
    ("What was the status of TikTok in the United States in early 2025?", "TikTok faced potential ban; brief shutdown in January 2025 before temporary extension"),
    ("What was the US national debt in early 2025?", "approximately $36 trillion"),
    ("What was the unemployment rate in the Eurozone in 2024?", "approximately 6.3%"),
    ("What was the GDP growth rate of China in 2024?", "approximately 5.0%"),
    ("What was the GDP growth rate of India in 2024?", "approximately 6.5-7.0%"),
    ("What was the global inflation rate in 2024?", "approximately 5.8% (declining from previous years)"),
    ("What new trade sanctions were imposed in 2024?", "Additional US and EU sanctions on Russia; US chip export restrictions on China expanded"),
    ("What was the status of the CHIPS Act implementation in 2024?", "Major grants awarded to Intel, TSMC, Samsung for US fab construction"),
    ("What was the Euro to US Dollar exchange rate in early 2025?", "approximately 1 EUR = 1.03-1.05 USD"),
    ("What was the UK interest rate (Bank of England base rate) in early 2025?", "approximately 4.5-4.75%"),
    ("What was the Japanese yen's exchange rate against the dollar in 2024?", "Weakened to approximately 150-160 yen per dollar"),
    ("What country experienced hyperinflation in 2024?", "Argentina, Venezuela, Zimbabwe among countries with very high inflation"),
    ("What was the global box office total for 2024?", "approximately $33-34 billion worldwide"),
    ("What major airline merger or acquisition occurred in 2024?", "Alaska Airlines completed acquisition of Hawaiian Airlines"),
    ("What was the most-used AI chatbot in 2024?", "ChatGPT by OpenAI"),
    ("What major social media policy change occurred in 2024?", "Multiple platform changes; Meta ended fact-checking program; Australia banned social media for under-16s"),
    ("What was the latest version of iOS released in 2024?", "iOS 18"),
    ("What was the latest version of Android released in 2024?", "Android 15"),
    ("What new Claude model did Anthropic release in 2025?", "Claude 3.7 Sonnet and Claude 4 family"),
]


def main():
    all_questions = []
    idx = 1

    categories = [
        ("easy", "easy", False, EASY),
        ("hard", "hard", True, HARD),
        ("medium", "borderline", True, BORDERLINE),
        ("hard", "temporal", True, TEMPORAL),
    ]

    for difficulty, category, expected_tool_use, questions in categories:
        for question, ground_truth in questions:
            all_questions.append({
                "id": f"fact_{idx:04d}",
                "question": question,
                "difficulty": difficulty,
                "expected_tool_use": expected_tool_use,
                "ground_truth": ground_truth,
                "category": category,
            })
            idx += 1

    out_path = Path("action_anchors/data/factual_recall.json")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(all_questions, f, indent=4, ensure_ascii=False)

    # Print category counts
    from collections import Counter
    cats = Counter(q["category"] for q in all_questions)
    print(f"Total questions: {len(all_questions)}")
    for cat, count in sorted(cats.items()):
        print(f"  {cat}: {count}")


if __name__ == "__main__":
    main()
